import { Inter } from "next/font/google";
import "./globals.css";
import AppContextProvider from "@/context/app/provider";
import CrmContextProvider from "@/context/crm/provider";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Easywork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="es" className="h-full light">
      <body className={inter.className}>
        <AppContextProvider>
          <CrmContextProvider>{children}</CrmContextProvider>
          <ToastContainer />
        </AppContextProvider>
      </body>
    </html>
  );
}
