import { Inter } from "next/font/google";
import "./globals.css";
import AppContextProvider from "@/context/app/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Easywork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="h-full">
      <body className={inter.className}>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
